################################################################################
#
# openthread
#
################################################################################

OPENTHREAD_VERSION = thread-reference-20250612
OPENTHREAD_SITE = https://github.com/openthread/ot-br-posix.git
OPENTHREAD_SITE_METHOD = git
OPENTHREAD_LICENSE = BSD-3-Clause
OPENTHREAD_LICENSE_FILES = LICENSE
OPENTHREAD_INSTALL_STAGING = NO
OPENTHREAD_SUPPORTS_IN_SOURCE_BUILD = NO

# Enable git submodules for build dependencies
OPENTHREAD_GIT_SUBMODULES = YES

# Dependencies
OPENTHREAD_DEPENDENCIES = \
	avahi \
	boost \
	dbus \
	jsoncpp \
	ncurses \
	protobuf \
	readline

# Base CMake configuration
OPENTHREAD_CONF_OPTS = \
	-DCMAKE_BUILD_TYPE=Release \
	-DBUILD_SHARED_LIBS=OFF \
	-DOTBR_BORDER_AGENT=$(if $(BR2_PACKAGE_OPENTHREAD_BORDER_AGENT),ON,OFF) \
	-DOTBR_DBUS=ON \
	-DOTBR_DNSSD_DISCOVERY_PROXY=ON \
	-DOTBR_SRP_ADVERTISING_PROXY=ON \
	-DOTBR_MDNS=avahi \
	-DOTBR_INFRA_IF_NAME=$(call qstrip,$(BR2_PACKAGE_OPENTHREAD_INFRA_IF_NAME)) \
	-DOT_PACKAGE_VERSION=$(OPENTHREAD_VERSION)

# Border routing
ifeq ($(BR2_PACKAGE_OPENTHREAD_BORDER_ROUTING),y)
OPENTHREAD_CONF_OPTS += -DOTBR_BORDER_ROUTING=ON
else
OPENTHREAD_CONF_OPTS += -DOTBR_BORDER_ROUTING=OFF
endif

# Backbone router
ifeq ($(BR2_PACKAGE_OPENTHREAD_BACKBONE_ROUTER),y)
OPENTHREAD_CONF_OPTS += \
	-DOTBR_BACKBONE_ROUTER=ON \
	-DOTBR_DUA_ROUTING=ON
OPENTHREAD_DEPENDENCIES += libnetfilter_queue
else
OPENTHREAD_CONF_OPTS += -DOTBR_BACKBONE_ROUTER=OFF
endif

# NAT64 support
ifeq ($(BR2_PACKAGE_OPENTHREAD_NAT64),y)
OPENTHREAD_CONF_OPTS += -DOTBR_NAT64=ON
else
OPENTHREAD_CONF_OPTS += -DOTBR_NAT64=OFF
endif

# DNS64 support
ifeq ($(BR2_PACKAGE_OPENTHREAD_DNS64),y)
OPENTHREAD_CONF_OPTS += -DOTBR_DNS64=ON
OPENTHREAD_DEPENDENCIES += dnsmasq bind
else
OPENTHREAD_CONF_OPTS += -DOTBR_DNS64=OFF
endif

# DHCPv6 PD
ifeq ($(BR2_PACKAGE_OPENTHREAD_DHCPV6_PD),y)
OPENTHREAD_CONF_OPTS += -DOTBR_DHCP6_PD=ON
else
OPENTHREAD_CONF_OPTS += -DOTBR_DHCP6_PD=OFF
endif

# Web GUI
ifeq ($(BR2_PACKAGE_OPENTHREAD_WEB_GUI),y)
OPENTHREAD_CONF_OPTS += -DOTBR_WEB=ON
OPENTHREAD_DEPENDENCIES += nodejs
else
OPENTHREAD_CONF_OPTS += -DOTBR_WEB=OFF
endif

# REST server
ifeq ($(BR2_PACKAGE_OPENTHREAD_REST_SERVER),y)
OPENTHREAD_CONF_OPTS += -DOTBR_REST=ON
else
OPENTHREAD_CONF_OPTS += -DOTBR_REST=OFF
endif

# Install init script
define OPENTHREAD_INSTALL_INIT_SYSV
	$(INSTALL) -D -m 0755 $(OPENTHREAD_PKGDIR)/S50otbr \
		$(TARGET_DIR)/etc/init.d/S50otbr
endef

$(eval $(cmake-package))
